# -*- coding: utf-8 -*-
"""Autogenerated file - DO NOT EDIT
If you spot a bug, please report it on the mailing list and/or change the generator."""

from nipype.interfaces.base import (CommandLine, CommandLineInputSpec, SEMLikeCommandLine, TraitedSpec,
                    File, Directory, traits, isdefined, InputMultiPath, OutputMultiPath)
import os


class BRAINSLabelStatsInputSpec(CommandLineInputSpec):
    imageVolume = File(argstr="--imageVolume %s", desc="Image Volume", exists=True)
    labelVolume = File(argstr="--labelVolume %s", desc="Label Volume", exists=True)
    labelNameFile = File(argstr="--labelNameFile %s", desc="Label Name File", exists=True)
    outputPrefixColumnNames = InputMultiPath(traits.Str, argstr="--outputPrefixColumnNames %s", desc="Prefix Column Name(s)", sep=",")
    outputPrefixColumnValues = InputMultiPath(traits.Str, argstr="--outputPrefixColumnValues %s", desc="Prefix Column Value(s)", sep=",")
    labelFileType = traits.Enum("unknown", "fslxml", "ants", "csv", argstr="--labelFileType %s", desc="Label File Type")
    numberOfHistogramBins = traits.Int(argstr="--numberOfHistogramBins %d", desc="Number Of Histogram Bins")
    minMaxType = traits.Enum("image", "label", "manual", argstr="--minMaxType %s", desc="Define minimim and maximum values based upon the image, label, or via command line")
    userDefineMinimum = traits.Float(argstr="--userDefineMinimum %f", desc="User define minimum value")
    userDefineMaximum = traits.Float(argstr="--userDefineMaximum %f", desc="User define maximum value")


class BRAINSLabelStatsOutputSpec(TraitedSpec):
    pass


class BRAINSLabelStats(SEMLikeCommandLine):
    """title: Label Statistics (BRAINS)

category: Quantification

description: Compute image statistics within each label of a label map.

version: 5.2.0

documentation-url: http://www.nitrc.org/plugins/mwiki/index.php/brains:BRAINSClassify

license: https://www.nitrc.org/svn/brains/BuildScripts/trunk/License.txt

contributor: Vincent A. Magnotta

acknowledgements: Funding for this work was provided by the Dana Foundation

"""

    input_spec = BRAINSLabelStatsInputSpec
    output_spec = BRAINSLabelStatsOutputSpec
    _cmd = " BRAINSLabelStats "
    _outputs_filenames = {}
    _redirect_x = False


class PETStandardUptakeValueComputationInputSpec(CommandLineInputSpec):
    petDICOMPath = Directory(argstr="--petDICOMPath %s", desc="Input path to a directory containing a PET volume containing DICOM header information for SUV computation", exists=True)
    petVolume = File(argstr="--petVolume %s", desc="Input PET volume for SUVbw computation (must be the same volume as pointed to by the DICOM path!).", exists=True)
    labelMap = File(argstr="--labelMap %s", desc="Input label volume containing the volumes of interest", exists=True)
    color = File(argstr="--color %s", desc="Color table to to map labels to colors and names", exists=True)
    csvFile = traits.Either(traits.Bool, File(), argstr="--csvFile %s", desc="A table holding the output SUV values in comma separated lines, one per label. Optional.", hash_files=False)
    OutputLabel = traits.Str(argstr="--OutputLabel %s", desc="List of labels for which SUV values were computed")
    OutputLabelValue = traits.Str(argstr="--OutputLabelValue %s", desc="List of label values for which SUV values were computed")
    SUVMax = traits.Str(argstr="--SUVMax %s", desc="SUV max for each label")
    SUVMean = traits.Str(argstr="--SUVMean %s", desc="SUV mean for each label")
    SUVMin = traits.Str(argstr="--SUVMin %s", desc="SUV minimum for each label")


class PETStandardUptakeValueComputationOutputSpec(TraitedSpec):
    csvFile = File(desc="A table holding the output SUV values in comma separated lines, one per label. Optional.", exists=True)


class PETStandardUptakeValueComputation(SEMLikeCommandLine):
    """title: PET Standard Uptake Value Computation

category: Quantification

description: Computes the standardized uptake value based on body weight. Takes an input PET image in DICOM and NRRD format (DICOM header must contain Radiopharmaceutical parameters). Produces a CSV file that contains patientID, studyDate, dose, labelID, suvmin, suvmax, suvmean, labelName for each volume of interest. It also displays some of the information as output strings in the GUI, the CSV file is optional in that case. The CSV file is appended to on each execution of the CLI.

version: 0.1.0.$Revision: 8595 $(alpha)

documentation-url: http://www.slicer.org/slicerWiki/index.php/Documentation/Nightly/Modules/ComputeSUVBodyWeight

contributor: Wendy Plesniak (SPL, BWH), Nicole Aucoin (SPL, BWH), Ron Kikinis (SPL, BWH)

acknowledgements: This work is funded by the Harvard Catalyst, and the National Alliance for Medical Image Computing (NAMIC), funded by the National Institutes of Health through the NIH Roadmap for Medical Research, Grant U54 EB005149.

"""

    input_spec = PETStandardUptakeValueComputationInputSpec
    output_spec = PETStandardUptakeValueComputationOutputSpec
    _cmd = " PETStandardUptakeValueComputation "
    _outputs_filenames = {'csvFile':'csvFile.csv'}
    _redirect_x = False
