# -*- coding: utf-8 -*-
"""Autogenerated file - DO NOT EDIT
If you spot a bug, please report it on the mailing list and/or change the generator."""

from nipype.interfaces.base import (CommandLine, CommandLineInputSpec, SEMLikeCommandLine, TraitedSpec,
                    File, Directory, traits, isdefined, InputMultiPath, OutputMultiPath)
import os


class AddScalarVolumesInputSpec(CommandLineInputSpec):
    inputVolume1 = File(argstr="%s", desc="Input volume 1", position=-3, exists=True)
    inputVolume2 = File(argstr="%s", desc="Input volume 2", position=-2, exists=True)
    outputVolume = traits.Either(traits.Bool, File(), argstr="%s", desc="Volume1 + Volume2", position=-1, hash_files=False)
    order = traits.Enum("0", "1", "2", "3", argstr="--order %s", desc="Interpolation order if two images are in different coordinate frames or have different sampling.")


class AddScalarVolumesOutputSpec(TraitedSpec):
    outputVolume = File(desc="Volume1 + Volume2", position=-1, exists=True)


class AddScalarVolumes(SEMLikeCommandLine):
    """title: Add Scalar Volumes

category: Filtering.Arithmetic

description: Adds two images. Although all image types are supported on input, only signed types are produced. The two images do not have to have the same dimensions.

version: 0.1.0.$Revision$(alpha)

documentation-url: https://www.slicer.org/wiki/Documentation/Nightly/Modules/Add

contributor: Bill Lorensen (GE)

acknowledgements: This work is part of the National Alliance for Medical Image Computing (NAMIC), funded by the National Institutes of Health through the NIH Roadmap for Medical Research, Grant U54 EB005149.

"""

    input_spec = AddScalarVolumesInputSpec
    output_spec = AddScalarVolumesOutputSpec
    _cmd = " AddScalarVolumes "
    _outputs_filenames = {'outputVolume':'outputVolume.nii'}
    _redirect_x = False


class CastScalarVolumeInputSpec(CommandLineInputSpec):
    InputVolume = File(argstr="%s", desc="Input volume, the volume to cast.", position=-2, exists=True)
    OutputVolume = traits.Either(traits.Bool, File(), argstr="%s", desc="Output volume, cast to the new type.", position=-1, hash_files=False)
    type = traits.Enum("Char", "UnsignedChar", "Short", "UnsignedShort", "Int", "UnsignedInt", "Float", "Double", argstr="--type %s", desc="Scalar data type for the new output volume.")


class CastScalarVolumeOutputSpec(TraitedSpec):
    OutputVolume = File(desc="Output volume, cast to the new type.", position=-1, exists=True)


class CastScalarVolume(SEMLikeCommandLine):
    """title: Cast Scalar Volume

category: Filtering.Arithmetic

description: Cast a volume to a given data type.\nUse at your own risk when casting an input volume into a lower precision type!\nAllows casting to the same type as the input volume.

version: 0.1.0.$Revision: 2104 $(alpha)

documentation-url: http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Modules/Cast

contributor: Nicole Aucoin (SPL, BWH), Ron Kikinis (SPL, BWH)

acknowledgements: This work is part of the National Alliance for Medical Image Computing (NAMIC), funded by the National Institutes of Health through the NIH Roadmap for Medical Research, Grant U54 EB005149.

"""

    input_spec = CastScalarVolumeInputSpec
    output_spec = CastScalarVolumeOutputSpec
    _cmd = " CastScalarVolume "
    _outputs_filenames = {'OutputVolume':'OutputVolume.nii'}
    _redirect_x = False


class MaskScalarVolumeInputSpec(CommandLineInputSpec):
    InputVolume = File(argstr="%s", desc="Input volume to be masked", position=-3, exists=True)
    MaskVolume = File(argstr="%s", desc="Label volume containing the mask", position=-2, exists=True)
    OutputVolume = traits.Either(traits.Bool, File(), argstr="%s", desc="Output volume: Input Volume masked by label value from Mask Volume", position=-1, hash_files=False)
    label = traits.Int(argstr="--label %d", desc="Label value in the Mask Volume to use as the mask")
    replace = traits.Int(argstr="--replace %d", desc="Value to use for the output volume outside of the mask")


class MaskScalarVolumeOutputSpec(TraitedSpec):
    OutputVolume = File(desc="Output volume: Input Volume masked by label value from Mask Volume", position=-1, exists=True)


class MaskScalarVolume(SEMLikeCommandLine):
    """title: Mask Scalar Volume

category: Filtering.Arithmetic

description: Masks two images. The output image is set to 0 everywhere except where the chosen label from the mask volume is present, at which point it will retain it's original values. The two images do not have to have the same dimensions.

version: 0.1.0.$Revision: 8595 $(alpha)

documentation-url: http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Modules/Mask

contributor: Nicole Aucoin (SPL, BWH), Ron Kikinis (SPL, BWH)

acknowledgements: This work is part of the National Alliance for Medical Image Computing (NAMIC), funded by the National Institutes of Health through the NIH Roadmap for Medical Research, Grant U54 EB005149.

"""

    input_spec = MaskScalarVolumeInputSpec
    output_spec = MaskScalarVolumeOutputSpec
    _cmd = " MaskScalarVolume "
    _outputs_filenames = {'OutputVolume':'OutputVolume.nii'}
    _redirect_x = False


class MultiplyScalarVolumesInputSpec(CommandLineInputSpec):
    inputVolume1 = File(argstr="%s", desc="Input volume 1", position=-3, exists=True)
    inputVolume2 = File(argstr="%s", desc="Input volume 2", position=-2, exists=True)
    outputVolume = traits.Either(traits.Bool, File(), argstr="%s", desc="Volume1 * Volume2", position=-1, hash_files=False)
    order = traits.Enum("0", "1", "2", "3", argstr="--order %s", desc="Interpolation order if two images are in different coordinate frames or have different sampling.")


class MultiplyScalarVolumesOutputSpec(TraitedSpec):
    outputVolume = File(desc="Volume1 * Volume2", position=-1, exists=True)


class MultiplyScalarVolumes(SEMLikeCommandLine):
    """title: Multiply Scalar Volumes

category: Filtering.Arithmetic

description: Multiplies two images. Although all image types are supported on input, only signed types are produced. The two images do not have to have the same dimensions.

version: 0.1.0.$Revision: 8595 $(alpha)

documentation-url: http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Modules/Multiply

contributor: Bill Lorensen (GE)

acknowledgements: This work is part of the National Alliance for Medical Image Computing (NAMIC), funded by the National Institutes of Health through the NIH Roadmap for Medical Research, Grant U54 EB005149.

"""

    input_spec = MultiplyScalarVolumesInputSpec
    output_spec = MultiplyScalarVolumesOutputSpec
    _cmd = " MultiplyScalarVolumes "
    _outputs_filenames = {'outputVolume':'outputVolume.nii'}
    _redirect_x = False


class SubtractScalarVolumesInputSpec(CommandLineInputSpec):
    inputVolume1 = File(argstr="%s", desc="Input volume 1", position=-3, exists=True)
    inputVolume2 = File(argstr="%s", desc="Input volume 2", position=-2, exists=True)
    outputVolume = traits.Either(traits.Bool, File(), argstr="%s", desc="Volume1 - Volume2", position=-1, hash_files=False)
    order = traits.Enum("0", "1", "2", "3", argstr="--order %s", desc="Interpolation order if two images are in different coordinate frames or have different sampling.")


class SubtractScalarVolumesOutputSpec(TraitedSpec):
    outputVolume = File(desc="Volume1 - Volume2", position=-1, exists=True)


class SubtractScalarVolumes(SEMLikeCommandLine):
    """title: Subtract Scalar Volumes

category: Filtering.Arithmetic

description: Subtracts two images. Although all image types are supported on input, only signed types are produced. The two images do not have to have the same dimensions.

version: 0.1.0.$Revision$(alpha)

documentation-url: http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Modules/Subtract

contributor: Bill Lorensen (GE)

acknowledgements: This work is part of the National Alliance for Medical Image Computing (NAMIC), funded by the National Institutes of Health through the NIH Roadmap for Medical Research, Grant U54 EB005149.

"""

    input_spec = SubtractScalarVolumesInputSpec
    output_spec = SubtractScalarVolumesOutputSpec
    _cmd = " SubtractScalarVolumes "
    _outputs_filenames = {'outputVolume':'outputVolume.nii'}
    _redirect_x = False
