# -*- coding: utf-8 -*-
"""Autogenerated file - DO NOT EDIT
If you spot a bug, please report it on the mailing list and/or change the generator."""

from nipype.interfaces.base import (CommandLine, CommandLineInputSpec, SEMLikeCommandLine, TraitedSpec,
                    File, Directory, traits, isdefined, InputMultiPath, OutputMultiPath)
import os


class ExtractSkeletonInputSpec(CommandLineInputSpec):
    InputImageFileName = File(argstr="%s", desc="Input image", position=-2, exists=True)
    OutputImageFileName = traits.Either(traits.Bool, File(), argstr="%s", desc="Skeleton of the input image", position=-1, hash_files=False)
    type = traits.Enum("1D", "2D", argstr="--type %s", desc="Type of skeleton to create")
    dontPrune = traits.Bool(argstr="--dontPrune ", desc="Return the full skeleton, not just the maximal skeleton")
    numPoints = traits.Int(argstr="--numPoints %d", desc="Number of points used to represent the skeleton")
    pointsFile = traits.Str(argstr="--pointsFile %s", desc="Name of the file to store the coordinates of the central (1D) skeleton points")
    fiducialsFile = File(argstr="--fiducialsFile %s", desc="Centerline points as markups curve")


class ExtractSkeletonOutputSpec(TraitedSpec):
    OutputImageFileName = File(desc="Skeleton of the input image", position=-1, exists=True)


class ExtractSkeleton(SEMLikeCommandLine):
    """title: Extract Skeleton

category: Filtering

description: Extract the skeleton of a binary object.  The skeleton can be limited to being a 1D curve or allowed to be a full 2D manifold.  The branches of the skeleton can be pruned so that only the maximal center skeleton is returned.

version: 0.1.0.$Revision: 2104 $(alpha)

documentation-url: http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Modules/ExtractSkeleton

contributor: Pierre Seroul (UNC), Martin Styner (UNC), Guido Gerig (UNC), Stephen Aylward (Kitware)

acknowledgements: The original implementation of this method was provided by ETH Zurich, Image Analysis Laboratory of Profs Olaf Kuebler, Gabor Szekely and Guido Gerig.  Martin Styner at UNC, Chapel Hill made enhancements.  Wrapping for Slicer was provided by Pierre Seroul and Stephen Aylward at Kitware, Inc.

"""

    input_spec = ExtractSkeletonInputSpec
    output_spec = ExtractSkeletonOutputSpec
    _cmd = " ExtractSkeleton "
    _outputs_filenames = {'OutputImageFileName':'OutputImageFileName.nii'}
    _redirect_x = False
