# -*- coding: utf-8 -*-
"""Autogenerated file - DO NOT EDIT
If you spot a bug, please report it on the mailing list and/or change the generator."""

from nipype.interfaces.base import (CommandLine, CommandLineInputSpec, SEMLikeCommandLine, TraitedSpec,
                    File, Directory, traits, isdefined, InputMultiPath, OutputMultiPath)
import os


class ThresholdScalarVolumeInputSpec(CommandLineInputSpec):
    InputVolume = File(argstr="%s", desc="Input volume", position=-2, exists=True)
    OutputVolume = traits.Either(traits.Bool, File(), argstr="%s", desc="Thresholded input volume", position=-1, hash_files=False)
    thresholdtype = traits.Enum("Below", "Above", "Outside", argstr="--thresholdtype %s", desc="What kind of threshold to perform. If Outside is selected, uses Upper and Lower values. If Below is selected, uses the ThresholdValue, if Above is selected, uses the ThresholdValue.")
    threshold = traits.Float(argstr="--threshold %f", desc="Threshold value")
    lower = traits.Float(argstr="--lower %f", desc="Lower threshold value")
    upper = traits.Float(argstr="--upper %f", desc="Upper threshold value")
    outsidevalue = traits.Float(argstr="--outsidevalue %f", desc="Set the voxels to this value if they fall outside the threshold range")
    negate = traits.Bool(argstr="--negate ", desc="Swap the outside value with the inside value.")


class ThresholdScalarVolumeOutputSpec(TraitedSpec):
    OutputVolume = File(desc="Thresholded input volume", position=-1, exists=True)


class ThresholdScalarVolume(SEMLikeCommandLine):
    """title: Threshold Scalar Volume

category: Filtering

description: <p>Threshold an image.</p><p>Set image values to a user-specified outside value if they are below, above, or between simple threshold values.</p><p>ThresholdAbove: The values greater than or equal to the threshold value are set to OutsideValue.</p><p>ThresholdBelow: The values less than or equal to the threshold value are set to OutsideValue.</p><p>ThresholdOutside: The values outside the range Lower-Upper are set to OutsideValue.</p>

version: 0.1.0.$Revision: 2104 $(alpha)

documentation-url: http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Modules/Threshold

contributor: Nicole Aucoin (SPL, BWH), Ron Kikinis (SPL, BWH), Julien Finet (Kitware)

acknowledgements: This work is part of the National Alliance for Medical Image Computing (NAMIC), funded by the National Institutes of Health through the NIH Roadmap for Medical Research, Grant U54 EB005149.

"""

    input_spec = ThresholdScalarVolumeInputSpec
    output_spec = ThresholdScalarVolumeOutputSpec
    _cmd = " ThresholdScalarVolume "
    _outputs_filenames = {'OutputVolume':'OutputVolume.nii'}
    _redirect_x = False
