# -*- coding: utf-8 -*-
"""Autogenerated file - DO NOT EDIT
If you spot a bug, please report it on the mailing list and/or change the generator."""

from nipype.interfaces.base import (CommandLine, CommandLineInputSpec, SEMLikeCommandLine, TraitedSpec,
                    File, Directory, traits, isdefined, InputMultiPath, OutputMultiPath)
import os


class DiffusionTensorTestInputSpec(CommandLineInputSpec):
    inputVolume = File(argstr="%s", desc="Input tensor volume to be filtered", position=-2, exists=True)
    outputVolume = traits.Either(traits.Bool, File(), argstr="%s", desc="Filtered tensor volume", position=-1, hash_files=False)


class DiffusionTensorTestOutputSpec(TraitedSpec):
    outputVolume = File(desc="Filtered tensor volume", position=-1, exists=True)


class DiffusionTensorTest(SEMLikeCommandLine):
    """title: Simple IO Test

category: Legacy.Work in Progress.Diffusion Tensor.Test

description: Simple test of tensor IO

version: 0.1.0.$Revision$(alpha)

contributor: Bill Lorensen (GE)

"""

    input_spec = DiffusionTensorTestInputSpec
    output_spec = DiffusionTensorTestOutputSpec
    _cmd = " DiffusionTensorTest "
    _outputs_filenames = {'outputVolume':'outputVolume.nii'}
    _redirect_x = False
