# -*- coding: utf-8 -*-
"""Autogenerated file - DO NOT EDIT
If you spot a bug, please report it on the mailing list and/or change the generator."""

from nipype.interfaces.base import (CommandLine, CommandLineInputSpec, SEMLikeCommandLine, TraitedSpec,
                    File, Directory, traits, isdefined, InputMultiPath, OutputMultiPath)
import os


class BRAINSStripRotationInputSpec(CommandLineInputSpec):
    inputVolume = File(argstr="--inputVolume %s", desc="Image To Warp", exists=True)
    outputVolume = traits.Either(traits.Bool, File(), argstr="--outputVolume %s", desc="Resulting deformed image", hash_files=False)
    transform = traits.Either(traits.Bool, File(), argstr="--transform %s", desc="Filename for the transform file", hash_files=False)


class BRAINSStripRotationOutputSpec(TraitedSpec):
    outputVolume = File(desc="Resulting deformed image", exists=True)
    transform = File(desc="Filename for the transform file", exists=True)


class BRAINSStripRotation(SEMLikeCommandLine):
    """title: BRAINS Strip Rotation

category: Utilities

description: Read an Image, write out same image with identity rotation matrix plus an ITK transform file

version: 5.2.0

license: https://www.nitrc.org/svn/brains/BuildScripts/trunk/License.txt

contributor: Kent WIlliams

"""

    input_spec = BRAINSStripRotationInputSpec
    output_spec = BRAINSStripRotationOutputSpec
    _cmd = " BRAINSStripRotation "
    _outputs_filenames = {'outputVolume':'outputVolume.nii','transform':'transform.h5'}
    _redirect_x = False
