# -*- coding: utf-8 -*-
"""Autogenerated file - DO NOT EDIT
If you spot a bug, please report it on the mailing list and/or change the generator."""

from nipype.interfaces.base import (CommandLine, CommandLineInputSpec, SEMLikeCommandLine, TraitedSpec,
                    File, Directory, traits, isdefined, InputMultiPath, OutputMultiPath)
import os


class SimpleRegionGrowingSegmentationInputSpec(CommandLineInputSpec):
    smoothingIterations = traits.Int(argstr="--smoothingIterations %d", desc="Number of smoothing iterations")
    timestep = traits.Float(argstr="--timestep %f", desc="Timestep for curvature flow")
    iterations = traits.Int(argstr="--iterations %d", desc="Number of iterations of region growing")
    multiplier = traits.Float(argstr="--multiplier %f", desc="Number of standard deviations to include in intensity model")
    neighborhood = traits.Int(argstr="--neighborhood %d", desc="The radius of the neighborhood over which to calculate intensity model")
    labelvalue = traits.Int(argstr="--labelvalue %d", desc="The integer value (0-255) to use for the segmentation results. This will determine the color of the segmentation that will be generated by the Region growing algorithm")
    seed = InputMultiPath(traits.List(traits.Float(), minlen=3, maxlen=3), argstr="--seed %s...", desc="Seed point(s) for region growing")
    inputVolume = File(argstr="%s", desc="Input volume to be filtered", position=-2, exists=True)
    outputVolume = traits.Either(traits.Bool, File(), argstr="%s", desc="Output filtered", position=-1, hash_files=False)


class SimpleRegionGrowingSegmentationOutputSpec(TraitedSpec):
    outputVolume = File(desc="Output filtered", position=-1, exists=True)


class SimpleRegionGrowingSegmentation(SEMLikeCommandLine):
    """title: Simple Region Growing Segmentation

category: Segmentation

description: A simple region growing segmentation algorithm based on intensity statistics. To create a list of fiducials (Seeds) for this algorithm, click on the tool bar icon of an arrow pointing to a sphere fiducial to enter the 'place a new object mode' and then use the Markups module. This module uses the Slicer Command Line Interface (CLI) and the ITK filters CurvatureFlowImageFilter and ConfidenceConnectedImageFilter.

version: 0.1.0.$Revision$(alpha)

documentation-url: http://www.slicer.org/slicerWiki/index.php/Documentation/Nightly/Modules/SimpleRegionGrowingSegmentation

contributor: Jim Miller (GE)

acknowledgements: This command module was derived from Insight/Examples (copyright) Insight Software Consortium

"""

    input_spec = SimpleRegionGrowingSegmentationInputSpec
    output_spec = SimpleRegionGrowingSegmentationOutputSpec
    _cmd = " SimpleRegionGrowingSegmentation "
    _outputs_filenames = {'outputVolume':'outputVolume.nii'}
    _redirect_x = False
