# -*- coding: utf-8 -*-
"""Autogenerated file - DO NOT EDIT
If you spot a bug, please report it on the mailing list and/or change the generator."""

from nipype.interfaces.base import (CommandLine, CommandLineInputSpec, SEMLikeCommandLine, TraitedSpec,
                    File, Directory, traits, isdefined, InputMultiPath, OutputMultiPath)
import os


class BRAINSABCInputSpec(CommandLineInputSpec):
    inputVolumes = InputMultiPath(File(exists=True), argstr="--inputVolumes %s...", desc="The list of input image files to be segmented.")
    atlasDefinition = File(argstr="--atlasDefinition %s", desc="Contains all parameters for Atlas", exists=True)
    restoreState = File(argstr="--restoreState %s", desc="The initial state for the registration process", exists=True)
    saveState = traits.Either(traits.Bool, File(), argstr="--saveState %s", desc="(optional) Filename to which save the final state of the registration", hash_files=False)
    inputVolumeTypes = InputMultiPath(traits.Str, argstr="--inputVolumeTypes %s", desc="The list of input image types corresponding to the inputVolumes.", sep=",")
    outputDir = traits.Either(traits.Bool, Directory(), argstr="--outputDir %s", desc="Ouput directory", hash_files=False)
    atlasToSubjectTransformType = traits.Enum("Identity", "Rigid", "Affine", "BSpline", "SyN", argstr="--atlasToSubjectTransformType %s", desc=" What type of linear transform type do you want to use to register the atlas to the reference subject image.")
    atlasToSubjectTransform = traits.Either(traits.Bool, File(), argstr="--atlasToSubjectTransform %s", desc="The transform from atlas to the subject", hash_files=False)
    atlasToSubjectInitialTransform = traits.Either(traits.Bool, File(), argstr="--atlasToSubjectInitialTransform %s", desc="The initial transform from atlas to the subject", hash_files=False)
    subjectIntermodeTransformType = traits.Enum("Identity", "Rigid", argstr="--subjectIntermodeTransformType %s", desc=" What type of transform type do you want to run intra subject registeration. Only Identity and Rigid are allowed.")
    outputVolumes = traits.Either(traits.Bool, InputMultiPath(File(), ), argstr="--outputVolumes %s...", desc="Corrected Output Images: should specify the same number of images as inputVolume, if only one element is given, then it is used as a file pattern where %s is replaced by the imageVolumeType, and %d by the index list location.", hash_files=False)
    outputLabels = traits.Either(traits.Bool, File(), argstr="--outputLabels %s", desc="Output Label Image", hash_files=False)
    outputDirtyLabels = traits.Either(traits.Bool, File(), argstr="--outputDirtyLabels %s", desc="Output Dirty Label Image", hash_files=False)
    posteriorTemplate = traits.Str(argstr="--posteriorTemplate %s", desc="filename template for Posterior output files")
    outputFormat = traits.Enum("NIFTI", "Meta", "Nrrd", argstr="--outputFormat %s", desc="Output format")
    interpolationMode = traits.Enum("BSpline", "NearestNeighbor", "WindowedSinc", "Linear", "ResampleInPlace", "Hamming", "Cosine", "Welch", "Lanczos", "Blackman", argstr="--interpolationMode %s", desc="Type of interpolation to be used when applying transform to moving volume.  Options are Linear, NearestNeighbor, BSpline, WindowedSinc, or ResampleInPlace.  The ResampleInPlace option will create an image with the same discrete voxel values and will adjust the origin and direction of the physical space interpretation.")
    maxIterations = traits.Int(argstr="--maxIterations %d", desc="Filter iterations")
    medianFilterSize = InputMultiPath(traits.Int, argstr="--medianFilterSize %s", desc="The radius for the optional MedianImageFilter preprocessing in all 3 directions.", sep=",")
    filterIteration = traits.Int(argstr="--filterIteration %d", desc="Filter iterations")
    filterTimeStep = traits.Float(argstr="--filterTimeStep %f", desc="Filter time step should be less than (PixelSpacing/(1^(DIM+1)), value is set to negative, then allow automatic setting of this value. ")
    filterMethod = traits.Enum("None", "CurvatureFlow", "GradientAnisotropicDiffusion", "Median", argstr="--filterMethod %s", desc="Filter method for preprocessing of registration")
    maxBiasDegree = traits.Int(argstr="--maxBiasDegree %d", desc="Maximum bias degree")
    useKNN = traits.Bool(argstr="--useKNN ", desc="Use the KNN stage of estimating posteriors.")
    purePlugsThreshold = traits.Float(argstr="--purePlugsThreshold %f", desc="If this threshold value is greater than zero, only pure samples are used to compute the distributions in EM classification, and only pure samples are used for KNN training. The default value is set to 0, that means not using pure plugs. However, a value between 0 and 1 should be set as the threshold if you want to activate using pure plugs option. Empirically a value of 0.1 is suggested.")
    numberOfSubSamplesInEachPlugArea = InputMultiPath(traits.Int, argstr="--numberOfSubSamplesInEachPlugArea %s", desc="Number of continous index samples taken at each direction of lattice space for each plug volume.", sep=",")
    atlasWarpingOff = traits.Bool(argstr="--atlasWarpingOff ", desc="Deformable registration of atlas to subject")
    gridSize = InputMultiPath(traits.Int, argstr="--gridSize %s", desc="Grid size for atlas warping with BSplines", sep=",")
    defaultSuffix = traits.Str(argstr="--defaultSuffix %s")
    implicitOutputs = traits.Either(traits.Bool, InputMultiPath(File(), ), argstr="--implicitOutputs %s...", desc="Outputs to be made available to NiPype. Needed because not all BRAINSABC outputs have command line arguments.", hash_files=False)
    debuglevel = traits.Int(argstr="--debuglevel %d", desc="Display debug messages, and produce debug intermediate results.  0=OFF, 1=Minimal, 10=Maximum debugging.")
    writeLess = traits.Bool(argstr="--writeLess ", desc="Does not write posteriors and filtered, bias corrected images")
    numberOfThreads = traits.Int(argstr="--numberOfThreads %d", desc="Explicitly specify the maximum number of threads to use.")


class BRAINSABCOutputSpec(TraitedSpec):
    saveState = File(desc="(optional) Filename to which save the final state of the registration", exists=True)
    outputDir = Directory(desc="Ouput directory", exists=True)
    atlasToSubjectTransform = File(desc="The transform from atlas to the subject", exists=True)
    atlasToSubjectInitialTransform = File(desc="The initial transform from atlas to the subject", exists=True)
    outputVolumes = OutputMultiPath(File(exists=True), desc="Corrected Output Images: should specify the same number of images as inputVolume, if only one element is given, then it is used as a file pattern where %s is replaced by the imageVolumeType, and %d by the index list location.", exists=True)
    outputLabels = File(desc="Output Label Image", exists=True)
    outputDirtyLabels = File(desc="Output Dirty Label Image", exists=True)
    implicitOutputs = OutputMultiPath(File(exists=True), desc="Outputs to be made available to NiPype. Needed because not all BRAINSABC outputs have command line arguments.", exists=True)


class BRAINSABC(SEMLikeCommandLine):
    """title: Intra-subject registration, bias Correction, and tissue classification (BRAINS)

category: Segmentation.Specialized

description: Atlas-based tissue segmentation method.  This is an algorithmic extension of work done by XXXX at UNC and Utah XXXX need more description here.

"""

    input_spec = BRAINSABCInputSpec
    output_spec = BRAINSABCOutputSpec
    _cmd = " BRAINSABC "
    _outputs_filenames = {'saveState':'saveState.h5','outputDir':'outputDir','atlasToSubjectTransform':'atlasToSubjectTransform.h5','atlasToSubjectInitialTransform':'atlasToSubjectInitialTransform.h5','outputVolumes':'outputVolumes.nii.gz','outputLabels':'outputLabels.nii.gz','outputDirtyLabels':'outputDirtyLabels.nii.gz','implicitOutputs':'implicitOutputs.nii.gz'}
    _redirect_x = False


class BRAINSCleanMaskInputSpec(CommandLineInputSpec):
    inputVolume = File(argstr="--inputVolume %s", desc="The mask image to be cleaned up.", exists=True)
    outputVolume = traits.Either(traits.Bool, File(), argstr="--outputVolume %s", desc="The cleaned mask image.", hash_files=False)
    numberOfThreads = traits.Int(argstr="--numberOfThreads %d", desc="Explicitly specify the maximum number of threads to use.")


class BRAINSCleanMaskOutputSpec(TraitedSpec):
    outputVolume = File(desc="The cleaned mask image.", exists=True)


class BRAINSCleanMask(SEMLikeCommandLine):
    """title: Mask Hole Filling (BRAINS)

category: Segmentation.Specialized

description: Cleans up a mask image by filling any holes

"""

    input_spec = BRAINSCleanMaskInputSpec
    output_spec = BRAINSCleanMaskOutputSpec
    _cmd = " BRAINSCleanMask "
    _outputs_filenames = {'outputVolume':'outputVolume.nii.gz'}
    _redirect_x = False


class BRAINSConstellationDetectorInputSpec(CommandLineInputSpec):
    houghEyeDetectorMode = traits.Int(argstr="--houghEyeDetectorMode %d", desc=",                 This flag controls the mode of Hough eye detector.  By default, value of 1 is for T1W images, while the value of 0 is for T2W and PD images.,             ")
    inputTemplateModel = File(argstr="--inputTemplateModel %s", desc="User-specified template model.,             ", exists=True)
    LLSModel = File(argstr="--LLSModel %s", desc="Linear least squares model filename in HD5 format", exists=True)
    inputVolume = File(argstr="--inputVolume %s", desc="Input image in which to find ACPC points", exists=True)
    outputVolume = traits.Either(traits.Bool, File(), argstr="--outputVolume %s", desc="ACPC-aligned output image with the same voxels as the input image, but updated origin, and direction cosign so that the AC point would fall at the physical location (0.0,0.0,0.0), and the mid-sagital plane is the plane where physical L/R coordinate is 0.0. No interpolation method is involved to create the \'outputVolume\', and this output image is created using \'resample in place\' filter.", hash_files=False)
    outputResampledVolume = traits.Either(traits.Bool, File(), argstr="--outputResampledVolume %s", desc="ACPC-aligned output image in a resampled uniform isotropic space.  Currently this is a 1mm, 256^3 image with identity direction cosign. Choose desired interpolation mode to generate the outputResampledVolume.", hash_files=False)
    outputTransform = traits.Either(traits.Bool, File(), argstr="--outputTransform %s", desc="The filename for the original space to ACPC alignment to be written (in .h5 format).,             ", hash_files=False)
    outputLandmarksInInputSpace = traits.Either(traits.Bool, File(), argstr="--outputLandmarksInInputSpace %s", desc=",               The filename for the new subject-specific landmark definition file in the same format produced by Slicer3 (.fcsv) with the landmarks in the original image space (the detected RP, AC, PC, and VN4) in it to be written.,             ", hash_files=False)
    outputLandmarksInACPCAlignedSpace = traits.Either(traits.Bool, File(), argstr="--outputLandmarksInACPCAlignedSpace %s", desc=",               The filename for the new subject-specific landmark definition file in the same format produced by Slicer3 (.fcsv) with the landmarks in the output image space (the detected RP, AC, PC, and VN4) in it to be written.,             ", hash_files=False)
    outputMRML = traits.Either(traits.Bool, File(), argstr="--outputMRML %s", desc=",               The filename for the new subject-specific scene definition file in the same format produced by Slicer3 (in .mrml format). Only the components that were specified by the user on command line would be generated. Compatible components include inputVolume, outputVolume, outputLandmarksInInputSpace, outputLandmarksInACPCAlignedSpace, and outputTransform.,             ", hash_files=False)
    outputVerificationScript = traits.Either(traits.Bool, File(), argstr="--outputVerificationScript %s", desc=",               The filename for the Slicer3 script that verifies the aligned landmarks against the aligned image file.  This will happen only in conjunction with saveOutputLandmarks and an outputVolume.,             ", hash_files=False)
    mspQualityLevel = traits.Int(argstr="--mspQualityLevel %d", desc=",                 Flag cotrols how agressive the MSP is estimated. 0=quick estimate (9 seconds), 1=normal estimate (11 seconds), 2=great estimate (22 seconds), 3=best estimate (58 seconds), NOTE: -1= Prealigned so no estimate!.,             ")
    otsuPercentileThreshold = traits.Float(argstr="--otsuPercentileThreshold %f", desc=",                 This is a parameter to FindLargestForegroundFilledMask, which is employed when acLowerBound is set and an outputUntransformedClippedVolume is requested.,             ")
    acLowerBound = traits.Float(argstr="--acLowerBound %f", desc=",                 When generating a resampled output image, replace the image with the BackgroundFillValue everywhere below the plane This Far in physical units (millimeters) below (inferior to) the AC point (as found by the model.)  The oversize default was chosen to have no effect.  Based on visualizing a thousand masks in the IPIG study, we recommend a limit no smaller than 80.0 mm.,             ")
    cutOutHeadInOutputVolume = traits.Bool(argstr="--cutOutHeadInOutputVolume ", desc=",                 Flag to cut out just the head tissue when producing an (un)transformed clipped volume.,             ")
    outputUntransformedClippedVolume = traits.Either(traits.Bool, File(), argstr="--outputUntransformedClippedVolume %s", desc="Output image in which to store neck-clipped input image, with the use of --acLowerBound and maybe --cutOutHeadInUntransformedVolume.", hash_files=False)
    rescaleIntensities = traits.Bool(argstr="--rescaleIntensities ", desc=",                 Flag to turn on rescaling image intensities on input.,             ")
    trimRescaledIntensities = traits.Float(argstr="--trimRescaledIntensities %f", desc=",                 Turn on clipping the rescaled image one-tailed on input.  Units of standard deviations above the mean.  Very large values are very permissive.  Non-positive value turns clipping off.  Defaults to removing 0.00001 of a normal tail above the mean.,             ")
    rescaleIntensitiesOutputRange = InputMultiPath(traits.Int, argstr="--rescaleIntensitiesOutputRange %s", desc=",                 This pair of integers gives the lower and upper bounds on the signal portion of the output image.  Out-of-field voxels are taken from BackgroundFillValue.,             ", sep=",")
    BackgroundFillValue = traits.Str(argstr="--BackgroundFillValue %s", desc="Fill the background of image with specified short int value. Enter number or use BIGNEG for a large negative number.")
    interpolationMode = traits.Enum("NearestNeighbor", "Linear", "BSpline", "WindowedSinc", "Hamming", "Cosine", "Welch", "Lanczos", "Blackman", argstr="--interpolationMode %s", desc="Type of interpolation to be used when applying transform to moving volume to create OutputResampledVolume.  Options are Linear, NearestNeighbor, BSpline, or WindowedSinc")
    forceACPoint = InputMultiPath(traits.Float, argstr="--forceACPoint %s", desc=",                 Manually specify the AC point from the original image in RAS coordinates (i.e. Slicer coordinates).,             ", sep=",")
    forcePCPoint = InputMultiPath(traits.Float, argstr="--forcePCPoint %s", desc=",                 Manually specify the PC point from the original image in RAS coordinates (i.e. Slicer coordinates).,             ", sep=",")
    forceVN4Point = InputMultiPath(traits.Float, argstr="--forceVN4Point %s", desc=",                 Manually specify the VN4 point from the original image in RAS coordinates (i.e. Slicer coordinates).,             ", sep=",")
    forceRPPoint = InputMultiPath(traits.Float, argstr="--forceRPPoint %s", desc=",                 Manually specify the RP point from the original image in RAS coordinates (i.e. Slicer coordinates).,             ", sep=",")
    inputLandmarksEMSP = File(argstr="--inputLandmarksEMSP %s", desc=",               The filename for the new subject-specific landmark definition file in the same format produced by Slicer3 (in .fcsv) with the landmarks in the estimated MSP aligned space to be loaded. The detector will only process landmarks not enlisted on the file.,             ", exists=True)
    forceHoughEyeDetectorReportFailure = traits.Bool(argstr="--forceHoughEyeDetectorReportFailure ", desc=",                 Flag indicates whether the Hough eye detector should report failure,             ")
    rmpj = traits.Float(argstr="--rmpj %f", desc=",               Search radius for MPJ in unit of mm,             ")
    rac = traits.Float(argstr="--rac %f", desc=",               Search radius for AC in unit of mm,             ")
    rpc = traits.Float(argstr="--rpc %f", desc=",               Search radius for PC in unit of mm,             ")
    rVN4 = traits.Float(argstr="--rVN4 %f", desc=",               Search radius for VN4 in unit of mm,             ")
    debug = traits.Bool(argstr="--debug ", desc=",               Show internal debugging information.,             ")
    verbose = traits.Bool(argstr="--verbose ", desc=",               Show more verbose output,             ")
    writeBranded2DImage = traits.Either(traits.Bool, File(), argstr="--writeBranded2DImage %s", desc=",               The filename for the 2D .png branded midline debugging image.  This will happen only in conjunction with requesting an outputVolume.,             ", hash_files=False)
    resultsDir = traits.Either(traits.Bool, Directory(), argstr="--resultsDir %s", desc=",               The directory for the debuging images to be written.,             ", hash_files=False)
    writedebuggingImagesLevel = traits.Int(argstr="--writedebuggingImagesLevel %d", desc=",                 This flag controls if debugging images are produced.  By default value of 0 is no images.  Anything greater than zero will be increasing level of debugging images.,             ")
    numberOfThreads = traits.Int(argstr="--numberOfThreads %d", desc="Explicitly specify the maximum number of threads to use.")
    atlasVolume = File(argstr="--atlasVolume %s", desc="Atlas volume image to be used for BRAINSFit registration to redefine the final ACPC-aligned transform by registering original input image to the Atlas image. The initial registration transform is created by passing BCD_ACPC_Landmarks and atlasLandmarks to BRAINSLandmarkInitializer. This flag should be used with atlasLandmarks and atlasLandmarkWeights flags. Note that using this flag causes that AC point in the final acpcLandmark file not be exactly placed at 0,0,0 coordinates.,             ", exists=True)
    atlasLandmarks = File(argstr="--atlasLandmarks %s", desc="Atlas landmarks to be used for BRAINSFit registration initialization,             ", exists=True)
    atlasLandmarkWeights = File(argstr="--atlasLandmarkWeights %s", desc="Weights associated with atlas landmarks to be used for BRAINSFit registration initialization,             ", exists=True)


class BRAINSConstellationDetectorOutputSpec(TraitedSpec):
    outputVolume = File(desc="ACPC-aligned output image with the same voxels as the input image, but updated origin, and direction cosign so that the AC point would fall at the physical location (0.0,0.0,0.0), and the mid-sagital plane is the plane where physical L/R coordinate is 0.0. No interpolation method is involved to create the \'outputVolume\', and this output image is created using \'resample in place\' filter.", exists=True)
    outputResampledVolume = File(desc="ACPC-aligned output image in a resampled uniform isotropic space.  Currently this is a 1mm, 256^3 image with identity direction cosign. Choose desired interpolation mode to generate the outputResampledVolume.", exists=True)
    outputTransform = File(desc="The filename for the original space to ACPC alignment to be written (in .h5 format).,             ", exists=True)
    outputLandmarksInInputSpace = File(desc=",               The filename for the new subject-specific landmark definition file in the same format produced by Slicer3 (.fcsv) with the landmarks in the original image space (the detected RP, AC, PC, and VN4) in it to be written.,             ", exists=True)
    outputLandmarksInACPCAlignedSpace = File(desc=",               The filename for the new subject-specific landmark definition file in the same format produced by Slicer3 (.fcsv) with the landmarks in the output image space (the detected RP, AC, PC, and VN4) in it to be written.,             ", exists=True)
    outputMRML = File(desc=",               The filename for the new subject-specific scene definition file in the same format produced by Slicer3 (in .mrml format). Only the components that were specified by the user on command line would be generated. Compatible components include inputVolume, outputVolume, outputLandmarksInInputSpace, outputLandmarksInACPCAlignedSpace, and outputTransform.,             ", exists=True)
    outputVerificationScript = File(desc=",               The filename for the Slicer3 script that verifies the aligned landmarks against the aligned image file.  This will happen only in conjunction with saveOutputLandmarks and an outputVolume.,             ", exists=True)
    outputUntransformedClippedVolume = File(desc="Output image in which to store neck-clipped input image, with the use of --acLowerBound and maybe --cutOutHeadInUntransformedVolume.", exists=True)
    writeBranded2DImage = File(desc=",               The filename for the 2D .png branded midline debugging image.  This will happen only in conjunction with requesting an outputVolume.,             ", exists=True)
    resultsDir = Directory(desc=",               The directory for the debuging images to be written.,             ", exists=True)


class BRAINSConstellationDetector(SEMLikeCommandLine):
    """title: Brain Landmark Constellation Detector (BRAINS)

category: Segmentation.Specialized

description: This program will find the mid-sagittal plane, a constellation of landmarks in a volume, and create an AC/PC aligned data set with the AC point at the center of the voxel lattice (labeled at the origin of the image physical space.)  Part of this work is an extention of the algorithms originally described by Dr. Babak A. Ardekani, Alvin H. Bachman, Model-based automatic detection of the anterior and posterior commissures on MRI scans, NeuroImage, Volume 46, Issue 3, 1 July 2009, Pages 677-682, ISSN 1053-8119, DOI: 10.1016/j.neuroimage.2009.02.030.  (http://www.sciencedirect.com/science/article/B6WNP-4VRP25C-4/2/8207b962a38aa83c822c6379bc43fe4c)

version: 5.2.0

documentation-url: http://www.nitrc.org/projects/brainscdetector/

license: https://www.nitrc.org/svn/brains/BuildScripts/trunk/License.txt

contributor: Hans J. Johnson (hans-johnson -at- uiowa.edu), Ali Ghayoor

acknowledgements: Hans Johnson(1,2,3); Ali Ghayoor(3); Wei Lu(3) 1=University of Iowa Department of Psychiatry, 2=University of Iowa Department of Biomedical Engineering, 3=University of Iowa Department of Electrical and Computer Engineering

"""

    input_spec = BRAINSConstellationDetectorInputSpec
    output_spec = BRAINSConstellationDetectorOutputSpec
    _cmd = " BRAINSConstellationDetector "
    _outputs_filenames = {'outputVolume':'outputVolume.nii.gz','outputResampledVolume':'outputResampledVolume.nii.gz','outputTransform':'outputTransform.h5','outputLandmarksInInputSpace':'outputLandmarksInInputSpace.fcsv','outputLandmarksInACPCAlignedSpace':'outputLandmarksInACPCAlignedSpace.fcsv','outputMRML':'outputMRML.mrml','outputVerificationScript':'outputVerificationScript.sh','outputUntransformedClippedVolume':'outputUntransformedClippedVolume.nii.gz','writeBranded2DImage':'writeBranded2DImage.png','resultsDir':'resultsDir'}
    _redirect_x = False


class BRAINSCreateLabelMapFromProbabilityMapsInputSpec(CommandLineInputSpec):
    inputProbabilityVolume = InputMultiPath(File(exists=True), argstr="--inputProbabilityVolume %s...", desc="The list of proobabilityimages.")
    priorLabelCodes = InputMultiPath(traits.Int, argstr="--priorLabelCodes %s", desc="A list of PriorLabelCode values used for coding the output label images", sep=",")
    foregroundPriors = InputMultiPath(traits.Int, argstr="--foregroundPriors %s", desc="A list: For each Prior Label, 1 if foreground, 0 if background", sep=",")
    nonAirRegionMask = File(argstr="--nonAirRegionMask %s", desc="a mask representing the \'NonAirRegion\' -- Just force pixels in this region to zero", exists=True)
    inclusionThreshold = traits.Float(argstr="--inclusionThreshold %f", desc="tolerance for inclusion")
    dirtyLabelVolume = traits.Either(traits.Bool, File(), argstr="--dirtyLabelVolume %s", desc="the labels prior to cleaning", hash_files=False)
    cleanLabelVolume = traits.Either(traits.Bool, File(), argstr="--cleanLabelVolume %s", desc="the foreground labels volume", hash_files=False)


class BRAINSCreateLabelMapFromProbabilityMapsOutputSpec(TraitedSpec):
    dirtyLabelVolume = File(desc="the labels prior to cleaning", exists=True)
    cleanLabelVolume = File(desc="the foreground labels volume", exists=True)


class BRAINSCreateLabelMapFromProbabilityMaps(SEMLikeCommandLine):
    """title: Create Label Map From Probability Maps (BRAINS)

category: Segmentation.Specialized

description: Given A list of Probability Maps, generate a LabelMap.

"""

    input_spec = BRAINSCreateLabelMapFromProbabilityMapsInputSpec
    output_spec = BRAINSCreateLabelMapFromProbabilityMapsOutputSpec
    _cmd = " BRAINSCreateLabelMapFromProbabilityMaps "
    _outputs_filenames = {'dirtyLabelVolume':'dirtyLabelVolume.nii','cleanLabelVolume':'cleanLabelVolume.nii'}
    _redirect_x = False


class BRAINSMultiSTAPLEInputSpec(CommandLineInputSpec):
    inputCompositeT1Volume = File(argstr="--inputCompositeT1Volume %s", desc="Composite T1, all label maps transofrmed into the space for this image.", exists=True)
    inputLabelVolume = InputMultiPath(File(exists=True), argstr="--inputLabelVolume %s...", desc="The list of proobabilityimages.")
    inputTransform = InputMultiPath(File(exists=True), argstr="--inputTransform %s...", desc="transforms to apply to label volumes")
    labelForUndecidedPixels = traits.Int(argstr="--labelForUndecidedPixels %d", desc="Label for undecided pixels")
    resampledVolumePrefix = traits.Str(argstr="--resampledVolumePrefix %s", desc="if given, write out resampled volumes with this prefix")
    skipResampling = traits.Bool(argstr="--skipResampling ", desc="Omit resampling images into reference space")
    outputMultiSTAPLE = traits.Either(traits.Bool, File(), argstr="--outputMultiSTAPLE %s", desc="the MultiSTAPLE average of input label volumes", hash_files=False)
    outputConfusionMatrix = traits.Either(traits.Bool, File(), argstr="--outputConfusionMatrix %s", desc="Confusion Matrix", hash_files=False)


class BRAINSMultiSTAPLEOutputSpec(TraitedSpec):
    outputMultiSTAPLE = File(desc="the MultiSTAPLE average of input label volumes", exists=True)
    outputConfusionMatrix = File(desc="Confusion Matrix", exists=True)


class BRAINSMultiSTAPLE(SEMLikeCommandLine):
    """title: Create best representative label map)

category: Segmentation.Specialized

description: given a list of label map images, create a representative/average label map.

"""

    input_spec = BRAINSMultiSTAPLEInputSpec
    output_spec = BRAINSMultiSTAPLEOutputSpec
    _cmd = " BRAINSMultiSTAPLE "
    _outputs_filenames = {'outputMultiSTAPLE':'outputMultiSTAPLE.nii','outputConfusionMatrix':'outputConfusionMatrixh5|mat|txt'}
    _redirect_x = False


class BRAINSROIAutoInputSpec(CommandLineInputSpec):
    inputVolume = File(argstr="--inputVolume %s", desc="The input image for finding the largest region filled mask.", exists=True)
    outputROIMaskVolume = traits.Either(traits.Bool, File(), argstr="--outputROIMaskVolume %s", desc="The ROI automatically found from the input image.", hash_files=False)
    outputVolume = traits.Either(traits.Bool, File(), argstr="--outputVolume %s", desc="The inputVolume with optional [maskOutput|cropOutput] to the region of the brain mask.", hash_files=False)
    maskOutput = traits.Bool(argstr="--maskOutput ", desc="The inputVolume multiplied by the ROI mask.")
    cropOutput = traits.Bool(argstr="--cropOutput ", desc="The inputVolume cropped to the region of the ROI mask.")
    otsuPercentileThreshold = traits.Float(argstr="--otsuPercentileThreshold %f", desc="Parameter to the Otsu threshold algorithm.")
    thresholdCorrectionFactor = traits.Float(argstr="--thresholdCorrectionFactor %f", desc="A factor to scale the Otsu algorithm's result threshold, in case clipping mangles the image.")
    closingSize = traits.Float(argstr="--closingSize %f", desc="The Closing Size (in millimeters) for largest connected filled mask.  This value is divided by image spacing and rounded to the next largest voxel number.")
    ROIAutoDilateSize = traits.Float(argstr="--ROIAutoDilateSize %f", desc="This flag is only relavent when using ROIAUTO mode for initializing masks.  It defines the final dilation size to capture a bit of background outside the tissue region.  At setting of 10mm has been shown to help regularize a BSpline registration type so that there is some background constraints to match the edges of the head better.")
    outputVolumePixelType = traits.Enum("float", "short", "ushort", "int", "uint", "uchar", argstr="--outputVolumePixelType %s", desc="The output image Pixel Type is the scalar datatype for representation of the Output Volume.")
    numberOfThreads = traits.Int(argstr="--numberOfThreads %d", desc="Explicitly specify the maximum number of threads to use.")


class BRAINSROIAutoOutputSpec(TraitedSpec):
    outputROIMaskVolume = File(desc="The ROI automatically found from the input image.", exists=True)
    outputVolume = File(desc="The inputVolume with optional [maskOutput|cropOutput] to the region of the brain mask.", exists=True)


class BRAINSROIAuto(SEMLikeCommandLine):
    """title: Foreground masking (BRAINS)

category: Segmentation.Specialized

description: This program is used to create a mask over the most prominant forground region in an image.  This is accomplished via a combination of otsu thresholding and a closing operation.  More documentation is available here: http://wiki.slicer.org/slicerWiki/index.php/Documentation/4.1/Modules/ForegroundMasking.

version: 5.2.0

license: https://www.nitrc.org/svn/brains/BuildScripts/trunk/License.txt

contributor: Hans J. Johnson, hans-johnson -at- uiowa.edu, http://www.psychiatry.uiowa.edu

acknowledgements: Hans Johnson(1,3,4); Kent Williams(1); Gregory Harris(1), Vincent Magnotta(1,2,3);  Andriy Fedorov(5), fedorov -at- bwh.harvard.edu (Slicer integration); (1=University of Iowa Department of Psychiatry, 2=University of Iowa Department of Radiology, 3=University of Iowa Department of Biomedical Engineering, 4=University of Iowa Department of Electrical and Computer Engineering, 5=Surgical Planning Lab, Harvard)

"""

    input_spec = BRAINSROIAutoInputSpec
    output_spec = BRAINSROIAutoOutputSpec
    _cmd = " BRAINSROIAuto "
    _outputs_filenames = {'outputROIMaskVolume':'outputROIMaskVolume.nii','outputVolume':'outputVolume.nii'}
    _redirect_x = False


class BinaryMaskEditorBasedOnLandmarksInputSpec(CommandLineInputSpec):
    inputBinaryVolume = File(argstr="--inputBinaryVolume %s", desc="Input binary image in which to be edited", exists=True)
    outputBinaryVolume = traits.Either(traits.Bool, File(), argstr="--outputBinaryVolume %s", desc="Output binary image in which to be edited", hash_files=False)
    inputLandmarksFilename = File(argstr="--inputLandmarksFilename %s", desc=" The filename for the  landmark definition file in the same format produced by Slicer3 (.fcsv). ", exists=True)
    inputLandmarkNames = InputMultiPath(traits.Str, argstr="--inputLandmarkNames %s", desc=" A target input landmark name to be edited. This should be listed in the inputLandmakrFilename Given. ", sep=",")
    setCutDirectionForLandmark = InputMultiPath(traits.Str, argstr="--setCutDirectionForLandmark %s", desc="Setting the cutting out direction of the input binary image to the one of anterior, posterior, left, right, superior or posterior. (ENUMERATION: ANTERIOR, POSTERIOR, LEFT, RIGHT, SUPERIOR, POSTERIOR) ", sep=",")
    setCutDirectionForObliquePlane = InputMultiPath(traits.Str, argstr="--setCutDirectionForObliquePlane %s", desc="If this is true, the mask will be thresholded out to the direction of inferior, posterior,  and/or left. Default behavrior is that cutting out to the direction of superior, anterior and/or right. ", sep=",")
    inputLandmarkNamesForObliquePlane = InputMultiPath(traits.Str, argstr="--inputLandmarkNamesForObliquePlane %s", desc=" Three subset landmark names of inputLandmarksFilename for a oblique plane computation. The plane computed for binary volume editing. ", sep=",")


class BinaryMaskEditorBasedOnLandmarksOutputSpec(TraitedSpec):
    outputBinaryVolume = File(desc="Output binary image in which to be edited", exists=True)


class BinaryMaskEditorBasedOnLandmarks(SEMLikeCommandLine):
    """title: BRAINS Binary Mask Editor Based On Landmarks(BRAINS)

category: Segmentation.Specialized

version: 5.2.0

documentation-url: http://www.nitrc.org/projects/brainscdetector/

"""

    input_spec = BinaryMaskEditorBasedOnLandmarksInputSpec
    output_spec = BinaryMaskEditorBasedOnLandmarksOutputSpec
    _cmd = " BinaryMaskEditorBasedOnLandmarks "
    _outputs_filenames = {'outputBinaryVolume':'outputBinaryVolume.nii'}
    _redirect_x = False


class ESLRInputSpec(CommandLineInputSpec):
    inputVolume = File(argstr="--inputVolume %s", desc="Input Label Volume", exists=True)
    outputVolume = traits.Either(traits.Bool, File(), argstr="--outputVolume %s", desc="Output Label Volume", hash_files=False)
    low = traits.Int(argstr="--low %d", desc="The lower bound of the labels to be used.")
    high = traits.Int(argstr="--high %d", desc="The higher bound of the labels to be used.")
    closingSize = traits.Int(argstr="--closingSize %d", desc="The closing size for hole filling.")
    openingSize = traits.Int(argstr="--openingSize %d", desc="The opening size for hole filling.")
    safetySize = traits.Int(argstr="--safetySize %d", desc="The safetySize size for the clipping region.")
    preserveOutside = traits.Bool(argstr="--preserveOutside ", desc="For values outside the specified range, preserve those values.")
    numberOfThreads = traits.Int(argstr="--numberOfThreads %d", desc="Explicitly specify the maximum number of threads to use.")


class ESLROutputSpec(TraitedSpec):
    outputVolume = File(desc="Output Label Volume", exists=True)


class ESLR(SEMLikeCommandLine):
    """title: Clean Contiguous Label Map (BRAINS)

category: Segmentation.Specialized

description: From a range of label map values, extract the largest contiguous region of those labels

"""

    input_spec = ESLRInputSpec
    output_spec = ESLROutputSpec
    _cmd = " ESLR "
    _outputs_filenames = {'outputVolume':'outputVolume.nii.gz'}
    _redirect_x = False


class RobustStatisticsSegmenterInputSpec(CommandLineInputSpec):
    expectedVolume = traits.Float(argstr="--expectedVolume %f", desc="The approximate volume of the object, in mL.")
    intensityHomogeneity = traits.Float(argstr="--intensityHomogeneity %f", desc="What is the homogeneity of intensity within the object? Given constant intensity at 1.0 score and extreme fluctuating intensity at 0.")
    curvatureWeight = traits.Float(argstr="--curvatureWeight %f", desc="Given sphere 1.0 score and extreme rough bounday/surface 0 score, what is the expected smoothness of the object?")
    labelValue = traits.Int(argstr="--labelValue %d", desc="Label value of the output image")
    maxRunningTime = traits.Float(argstr="--maxRunningTime %f", desc="The program will stop if this time is reached.")
    originalImageFileName = File(argstr="%s", desc="Original image to be segmented", position=-3, exists=True)
    labelImageFileName = File(argstr="%s", desc="Label image for initialization", position=-2, exists=True)
    segmentedImageFileName = traits.Either(traits.Bool, File(), argstr="%s", desc="Segmented image", position=-1, hash_files=False)


class RobustStatisticsSegmenterOutputSpec(TraitedSpec):
    segmentedImageFileName = File(desc="Segmented image", position=-1, exists=True)


class RobustStatisticsSegmenter(SEMLikeCommandLine):
    """title: Robust Statistics Segmenter

category: Segmentation.Specialized

description: Active contour segmentation using robust statistic.

version: 1.0

documentation-url: http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Modules/RobustStatisticsSegmenter

contributor: Yi Gao (gatech), Allen Tannenbaum (gatech), Ron Kikinis (SPL, BWH)

acknowledgements: This work is part of the National Alliance for Medical Image Computing (NAMIC), funded by the National Institutes of Health

"""

    input_spec = RobustStatisticsSegmenterInputSpec
    output_spec = RobustStatisticsSegmenterOutputSpec
    _cmd = " RobustStatisticsSegmenter "
    _outputs_filenames = {'segmentedImageFileName':'segmentedImageFileName.nii'}
    _redirect_x = False


class simpleEMInputSpec(CommandLineInputSpec):
    t1Volume = File(argstr="--t1Volume %s", desc="T1 Volume", exists=True)
    t2Volume = File(argstr="--t2Volume %s", desc="T2 Volume", exists=True)
    pdVolume = File(argstr="--pdVolume %s", desc="PD Volume", exists=True)
    templateVolume = File(argstr="--templateVolume %s", desc="template Volume", exists=True)
    priorsList = InputMultiPath(traits.Str, argstr="--priorsList %s", desc=" number of input should same to the number of priorsList", sep=",")
    priorsWeightList = InputMultiPath(traits.Float, argstr="--priorsWeightList %s", desc=" number of input should same to the number of priorsList", sep=",")
    likelihoodTolerance = traits.Float(argstr="--likelihoodTolerance %f", desc=" a convergence parameter (0 indicates take the default from the EMSegmentationFilter constructor.)")
    warp = traits.Bool(argstr="--warp ")
    degreeOfBiasFieldCorrection = traits.Int(argstr="--degreeOfBiasFieldCorrection %d")
    maxIteration = traits.Int(argstr="--maxIteration %d")
    OutputFileNamePrefix = traits.Str(argstr="--OutputFileNamePrefix %s")
    inputPixelType = traits.Enum("usigned char", "short", "unsigned short", "int", "unsigned int", "long", "float", "double", argstr="--inputPixelType %s", desc="Input Type")
    outputPixelType = traits.Enum("unsigbed char", "short", "unsigned short", "int", "unsigned int", "long", "float", "double", argstr="--outputPixelType %s", desc="Input Type")
    priorPixelType = traits.Enum("unsigbed char", "short", "unsigned short", "int", "unsigned int", "long", "float", "double", argstr="--priorPixelType %s", desc="prior Type")


class simpleEMOutputSpec(TraitedSpec):
    pass


class simpleEM(SEMLikeCommandLine):
    """title: simpleEM (BRAINS)

category: Segmentation.Specialized

description: Atlas-based tissue segmentation method

"""

    input_spec = simpleEMInputSpec
    output_spec = simpleEMOutputSpec
    _cmd = " simpleEM "
    _outputs_filenames = {}
    _redirect_x = False
