# -*- coding: utf-8 -*-
"""Autogenerated file - DO NOT EDIT
If you spot a bug, please report it on the mailing list and/or change the generator."""

from nipype.interfaces.base import (CommandLine, CommandLineInputSpec, SEMLikeCommandLine, TraitedSpec,
                    File, Directory, traits, isdefined, InputMultiPath, OutputMultiPath)
import os


class BRAINSPosteriorToContinuousClassInputSpec(CommandLineInputSpec):
    inputWhiteVolume = File(argstr="--inputWhiteVolume %s", desc="White Matter Posterior Volume", exists=True)
    inputBasalGmVolume = File(argstr="--inputBasalGmVolume %s", desc="Basal Grey Matter Posterior Volume", exists=True)
    inputSurfaceGmVolume = File(argstr="--inputSurfaceGmVolume %s", desc="Surface Grey Matter Posterior Volume", exists=True)
    inputCsfVolume = File(argstr="--inputCsfVolume %s", desc="CSF Posterior Volume", exists=True)
    inputVbVolume = File(argstr="--inputVbVolume %s", desc="Venous Blood Posterior Volume", exists=True)
    inputCrblGmVolume = File(argstr="--inputCrblGmVolume %s", desc="Cerebellum Grey Matter Posterior Volume", exists=True)
    inputCrblWmVolume = File(argstr="--inputCrblWmVolume %s", desc="Cerebellum White Matter Posterior Volume", exists=True)
    outputVolume = traits.Either(traits.Bool, File(), argstr="--outputVolume %s", desc="Output Continuous Tissue Classified Image", hash_files=False)


class BRAINSPosteriorToContinuousClassOutputSpec(TraitedSpec):
    outputVolume = File(desc="Output Continuous Tissue Classified Image", exists=True)


class BRAINSPosteriorToContinuousClass(SEMLikeCommandLine):
    """title: Tissue Classification

category: BRAINS.Classify

description: This program will generate an 8-bit continuous tissue classified image based on BRAINSABC posterior images.

version: 5.2.0

documentation-url: http://www.nitrc.org/plugins/mwiki/index.php/brains:BRAINSClassify

license: https://www.nitrc.org/svn/brains/BuildScripts/trunk/License.txt

contributor: Vincent A. Magnotta

acknowledgements: Funding for this work was provided by NIH/NINDS award NS050568

"""

    input_spec = BRAINSPosteriorToContinuousClassInputSpec
    output_spec = BRAINSPosteriorToContinuousClassOutputSpec
    _cmd = " BRAINSPosteriorToContinuousClass "
    _outputs_filenames = {'outputVolume':'outputVolume'}
    _redirect_x = False
