# -*- coding: utf-8 -*-
"""Autogenerated file - DO NOT EDIT
If you spot a bug, please report it on the mailing list and/or change the generator."""

from nipype.interfaces.base import (CommandLine, CommandLineInputSpec, SEMLikeCommandLine, TraitedSpec,
                    File, Directory, traits, isdefined, InputMultiPath, OutputMultiPath)
import os


class BRAINSTalairachInputSpec(CommandLineInputSpec):
    AC = InputMultiPath(traits.Float, argstr="--AC %s", desc="Location of AC Point ", sep=",")
    ACisIndex = traits.Bool(argstr="--ACisIndex ", desc="AC Point is Index")
    PC = InputMultiPath(traits.Float, argstr="--PC %s", desc="Location of PC Point ", sep=",")
    PCisIndex = traits.Bool(argstr="--PCisIndex ", desc="PC Point is Index")
    SLA = InputMultiPath(traits.Float, argstr="--SLA %s", desc="Location of SLA Point ", sep=",")
    SLAisIndex = traits.Bool(argstr="--SLAisIndex ", desc="SLA Point is Index")
    IRP = InputMultiPath(traits.Float, argstr="--IRP %s", desc="Location of IRP Point ", sep=",")
    IRPisIndex = traits.Bool(argstr="--IRPisIndex ", desc="IRP Point is Index")
    inputLandmarksFile = File(argstr="--inputLandmarksFile %s", desc="input landmarks file: *.fcsv", exists=True)
    inputVolume = File(argstr="--inputVolume %s", desc="Input image used to define physical space of images", exists=True)
    outputBox = traits.Either(traits.Bool, File(), argstr="--outputBox %s", desc="Name of the resulting Talairach Bounding Box file", hash_files=False)
    outputGrid = traits.Either(traits.Bool, File(), argstr="--outputGrid %s", desc="Name of the resulting Talairach Grid file", hash_files=False)


class BRAINSTalairachOutputSpec(TraitedSpec):
    outputBox = File(desc="Name of the resulting Talairach Bounding Box file", exists=True)
    outputGrid = File(desc="Name of the resulting Talairach Grid file", exists=True)


class BRAINSTalairach(SEMLikeCommandLine):
    """title: BRAINS Talairach

category: BRAINS.Segmentation

description: This program creates a VTK structured grid defining the Talairach coordinate system based on four points: AC, PC, IRP, and SLA. The resulting structred grid can be written as either a classic VTK file or the new VTK XML file format. Two representations of the resulting grid can be written. The first is a bounding box representation that also contains the location of the AC and PC points. The second representation is the full Talairach grid representation that includes the additional rows of boxes added to the inferior allowing full coverage of the cerebellum.

version: 5.2.0

documentation-url: http://www.nitrc.org/plugins/mwiki/index.php/brains:BRAINSTalairach

license: https://www.nitrc.org/svn/brains/BuildScripts/trunk/License.txt

contributor: Steven Dunn and Vincent Magnotta

acknowledgements: Funding for this work was provided by NIH/NINDS award NS050568

"""

    input_spec = BRAINSTalairachInputSpec
    output_spec = BRAINSTalairachOutputSpec
    _cmd = " BRAINSTalairach "
    _outputs_filenames = {'outputBox':'outputBox','outputGrid':'outputGrid'}
    _redirect_x = False


class BRAINSTalairachMaskInputSpec(CommandLineInputSpec):
    inputVolume = File(argstr="--inputVolume %s", desc="Input image used to define physical space of resulting mask", exists=True)
    talairachParameters = File(argstr="--talairachParameters %s", desc="Name of the Talairach parameter file.", exists=True)
    talairachBox = File(argstr="--talairachBox %s", desc="Name of the Talairach box file.", exists=True)
    hemisphereMode = traits.Enum("left", "right", "both", argstr="--hemisphereMode %s", desc="Mode for box creation: left, right, both")
    expand = traits.Bool(argstr="--expand ", desc="Expand exterior box to include surface CSF")
    outputVolume = traits.Either(traits.Bool, File(), argstr="--outputVolume %s", desc="Output filename for the resulting binary image", hash_files=False)


class BRAINSTalairachMaskOutputSpec(TraitedSpec):
    outputVolume = File(desc="Output filename for the resulting binary image", exists=True)


class BRAINSTalairachMask(SEMLikeCommandLine):
    """title: Talairach Mask

category: BRAINS.Segmentation

description: This program creates a binary image representing the specified Talairach region. The input is an example image to define the physical space for the resulting image, the Talairach grid representation in VTK format, and the file containing the Talairach box definitions to be generated. These can be combined in BRAINS to create a label map using the procedure Brains::WorkupUtils::CreateLabelMapFromBinaryImages.

version: 5.2.0

documentation-url: http://www.nitrc.org/plugins/mwiki/index.php/brains:BRAINSTalairachMask

license: https://www.nitrc.org/svn/brains/BuildScripts/trunk/License.txt

contributor: Steven Dunn and Vincent Magnotta

acknowledgements: Funding for this work was provided by NIH/NINDS award NS050568

"""

    input_spec = BRAINSTalairachMaskInputSpec
    output_spec = BRAINSTalairachMaskOutputSpec
    _cmd = " BRAINSTalairachMask "
    _outputs_filenames = {'outputVolume':'outputVolume.nii'}
    _redirect_x = False
